# The problem:

# Bag of Words

# CountVectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
count_vect = CountVectorizer()

In [29]:
a = 'Ana are mar si mar si mar'
b = 'mar si par'

In [30]:
r = count_vect.fit_transform([a, b])

In [31]:
r

<2x5 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [32]:
r.toarray()

array([[1, 1, 3, 0, 2],
       [0, 0, 1, 1, 1]], dtype=int64)

In [33]:
count_vect.vocabulary_

{'ana': 0, 'are': 1, 'mar': 2, 'si': 4, 'par': 3}

# Tf or Tfidf Transformer

In [39]:
from sklearn.feature_extraction.text import TfidfTransformer
termfrecv_transformer = TfidfTransformer(use_idf=False)
termfrecv_transformer.fit(r)
r2 = termfrecv_transformer.transform(r)

In [41]:
r2.todense()

matrix([[0.25819889, 0.25819889, 0.77459667, 0.        , 0.51639778],
        [0.        , 0.        , 0.57735027, 0.57735027, 0.57735027]])

In [43]:
r2.shape

(2, 5)

In [46]:
termfrecv_transformer = TfidfTransformer(use_idf=True)
termfrecv_transformer.fit(r)
r2 = termfrecv_transformer.transform(r)
r2.todense()

matrix([[0.34137106, 0.34137106, 0.72866497, 0.        , 0.48577665],
        [0.        , 0.        , 0.50154891, 0.70490949, 0.50154891]])

# Tfidf Vectorizer

In [81]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(min_df=0, max_df=3)
tfidf_vect.fit([a,b])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=3, max_features=None, min_df=0,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words=None, strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [82]:
r = tfidf_vect.transform([a,b])

In [83]:
r.todense()

matrix([[0.34137106, 0.34137106, 0.72866497, 0.        , 0.48577665],
        [0.        , 0.        , 0.50154891, 0.70490949, 0.50154891]])

In [84]:
r.shape

(2, 5)

In [85]:
tfidf_vect.vocabulary_

{'ana': 0, 'are': 1, 'mar': 2, 'si': 4, 'par': 3}

In [86]:
# what happends if we lower max_df=1?

# Ngrams

In [87]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vect = TfidfVectorizer(min_df=0, max_df=2, ngram_range=(1, 2))
tfidf_vect.fit([a,b])
r = tfidf_vect.transform([a,b])
r.todense()

matrix([[0.24539491, 0.24539491, 0.24539491, 0.24539491, 0.5238015 ,
         0.349201  , 0.        , 0.349201  , 0.49078982, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.37930349,
         0.37930349, 0.53309782, 0.37930349, 0.        , 0.53309782]])

In [88]:
r.shape

(2, 10)

In [89]:
tfidf_vect.vocabulary_

{'ana': 0,
 'are': 2,
 'mar': 4,
 'si': 7,
 'ana are': 1,
 'are mar': 3,
 'mar si': 5,
 'si mar': 8,
 'par': 6,
 'si par': 9}

In [90]:
# why did this happen?

# Summary